package com.universalsompo.meta.metaapp.motor.constants;

public class UrlConstants {
//     private static final String BASE_URL = "http://usgiapidemo.metacar.in/AL_Mobile_App.svc/";

//     private static final String BASE_URL = "http://14.141.41.50:81/AL_Mobile_App.svc/";
     private static final String BASE_URL = "http://uatpulz.universalsompo.in:81/AL_Mobile_App.svc.svc/";
    //   1-09-2021
//    private static final String BASE_URL ="http://mobile.universalsompo.in/Mobile_API/AL_Mobile_App.svc/";
//     private static final String BASE_URL = "http://mobile.universalsompo.in/Mobile_API/AL_Mobile_App.svc/";
//    private static final String BASE_URL = "http://mobile.universalsompo.in/Mobile_UAT_API/AL_Mobile_App.svc/";
    public static final String URL_LOGIN = BASE_URL + "LoginApp";
    public static final String URL_REGISTRATION = BASE_URL + "UserRegistration";
    public static final String URL_VERIFY_OTP = BASE_URL + "OTPAuthenticate";
    public static final String URL_RESEND_OTP = BASE_URL + "ResendOTP";
    public static final String URL_DELETE_OTHER_POLICY = BASE_URL + "DeleteOtherPolicy";
    public static final String CLAIM_POLICY_WRITEUP = BASE_URL + "GetPolicyWriteUp";
    public static final String DOWNLOAD_CLAIM_FORM = BASE_URL + "DownloadClaimForm";
    public static final String GET_COVERAGE_DETAIL = BASE_URL + "GetCoverageDetails";
    public static final String CALL_CLAIM_TRUE = BASE_URL + "ClaimThroughCall";
    public static final String GET_GARAGE_LIST = BASE_URL + "GetGarageLocation";
    public static final String GET_STATE = BASE_URL + "GetState";
    public static final String GET_CITY = BASE_URL + "GetCity";
    public static final String GET_CITY_BASED_ON_NAME = BASE_URL + "GetCityOnStateName";
    public static final String GET_VEHICLE = BASE_URL + "GetVehicle";
    public static final String GET_SLIDER_IMAGE = BASE_URL + "GetSliderImage";
    public static final String GET_RENEWAL_POLICY_URL = BASE_URL + "GetRenewURL";
    public static final String RENEWAL_POLICY_DETAIL_URL = BASE_URL + "TWUpdateRenewalPolicy";
    public static final String GET_COMAPANY_LIST = BASE_URL + "GetInsCompany";
    public static final String GET_ALL_GARAGE = BASE_URL + "GetAllGarage";
    public static final String GET_ALL_Hospital = BASE_URL + "GetAllHospital";
    public static final String DOCUMENT_IMG_PREVIEW = BASE_URL + "GetELockerFiles";
    public static final String DOCUMENT_IMG_UPLOAD = BASE_URL + "SaveLockerData";
    public static final String DOCUMENT_IMG_DELETE = BASE_URL + "DeleteELockerFile";
    public static final String GET_PROFILE_DETAIL = BASE_URL + "GetUserDetail";
    public static final String PROFILE_UPDATE = BASE_URL + "UpdateUser";
    public static final String GET_CALL_US_NO = BASE_URL + "GetCustomerCareNo";
    public static final String PRIVACY_POLICY = BASE_URL + "GetEditorContent";
    public static final String ABOUT_US = BASE_URL + "GetEditorContent";
    public static final String TERMS_CONDITIONS = BASE_URL + "GetEditorContent";
    public static final String SEND_MAIL_CLAIM_FORM = BASE_URL + "MailClaimForm";
    public static final String VEHICLE_KMS_INFO = BASE_URL + "GetServiceDetails";
    public static final String GET_TRACKING_STATUS = BASE_URL + "ClaimCount";
    public static final String GET_REG_NO_LIST_ON_CLAIM = BASE_URL + "GetRegNoForClaimStatus";
    public static final String GET_POLICY_DETAIL_ON_REGNO = BASE_URL + "GetPolicyDetailsOnRegNo";
    public static final String GET_TRACKING_DETAIL = BASE_URL + "GetTrackingStatus";
    public static final String UPDATE_REFERENCE_NO = BASE_URL + "UpdateRefrenceNo";
    public static final String GET_MULTIBRAND_LIST = BASE_URL + "GetVendorsOnCity";
    public static final String GET_SERVICE_BENDER_DETAILS = BASE_URL + "GetVendorsDetails";
    public static final String GET_VISITOR_COUNT = BASE_URL + "SaveVisitorDetails";
    public static final String GET_SERVICE_PROVIDER_CITY = BASE_URL + "GetCityOnVendorType";
    public static final String GET_CONTENT = BASE_URL + "GetVideoContentDetails";
    public static final String SEND_DEVICE_DETAIL = BASE_URL + "SaveUserDeviceDetails";
    public static final String SERVICE_ITEMS = BASE_URL + "GetAlmondzVendors";
    public static final String GET_SETTLED_CLAIM_LIST = BASE_URL + "GetSettledClaimPolicy";
    public static final String UPDATE_REFERENCE_NO_FOR_MULTIPLE = BASE_URL + "UpdateRefrenceNo";
    public static final String CHECK_NOTIFICATION = BASE_URL + "GetNotificationMessage";
    public static final String MARK_READ_NOTIFICATION = BASE_URL + "MarkRead";
    public static final String CLEAR_NOTIFICATION = BASE_URL + "ClearNotification";
    public static final String GET_FUEL_CITY_LIST = BASE_URL + "GetFuelPriceCity";
    public static final String GET_FUEL_PRICE_LIST = BASE_URL + "GetFuelPrice";
    public static final String URL_LOGOUT_USER = BASE_URL + "UserLogOut";
    public static final String URL_STATUS_USER = BASE_URL + "GetUserActiveStatus";
    public static final String URL_CHECK_DEVICE_STATUS = BASE_URL + "CheckUserDeviceStatus";
    public static final String LAST_ACTIVITY_LOG = BASE_URL + "AppUserLogInsert";
    public static final String APP_USER_LOG_DATA_PUSH = BASE_URL + "AppUserLogDataPush";
    public static final String OTP_AUTHENTICATE_SIGN_UP = BASE_URL + "App_OTPRegValidation";
    public static final String UPDATE_USER_DEVICE_ID = BASE_URL + "UpdateUserDeviceDetails";
    public static final String GET_RSS_FEED = BASE_URL + "GetRssFeed";
    public static final String UNIVERSAL_POLICY = BASE_URL + "UnivSompo_GetPolicyList";
    public static final String VIEW_UNIVERSAL_POLICY_DETAIL = BASE_URL + "UnivSompo_ViewPolicy";
    public static final String URL_LINK_NEW_POLICY = BASE_URL + "UnivSompo_SaveUpdateOtherPolicy";
    public static final String GET_CLAIM_POLICY_DETAIL1 = BASE_URL + "UnivSompo_GetClaimPolicyDetails";
    public static final String EXPIRED_POLICY_LIST = BASE_URL + "UnivSompo_GetExpiredPolicyList";
    public static final String VIEW_META_OWN_POLICY = BASE_URL + "UnivSompo_ViewPolicyDetails";
    public static final String EMAIL_API = BASE_URL + "UnivSompo_MailPolicyDoc";
    public static final String GET_DOC_CATEGORY = BASE_URL + "UnivSompo_GetDocCategory";
    public static final String GET_REG_NO_LIST_DOCUMENT = BASE_URL + "UnivSompo_GetRegistrationOnUserAndPolicy";
    public static final String GET_LIST_OF_CARS_FOR_SERVICE1 = BASE_URL + "UnivSompo_GetRegistration";
    public static final String GET_OEM_MULTIBRAND_1 = BASE_URL + "UnivSompo_GetOEMMultibrand";
    public static final String GET_OEM_DETAILS = BASE_URL + "UnivSompo_GetOEMDetails";
    public static final String VEHICLE_REGISTRATION_NUMBER1 = BASE_URL + "UnivSompo_GetRegistration";
    public static final String VEHICLE_REGISTRATION_MAKE_MODEL_1 = BASE_URL + "UnivSompo_GetVehicleDetails";
    public static final String SAVE_CLAIM_POLICY_DETAIL = BASE_URL + "UnivSompo_MotorClaimIntimation";
    public static final String MOTOR_CLAIM_STATUS_LIST = BASE_URL + "UnivSompo_GetMotorPolicyClaimList";
    public static final String GET_HELP = BASE_URL + "MotorHelp_GetCategory1List";
    public static final String GET_HELP1 = BASE_URL + "MotorHelp_GetCategory2List";
    public static final String GET_HELP2 = BASE_URL + "MotorHelp_GetCategory3List";
    public static final String GET_HELP3 = BASE_URL + "MotorHelp_GetCategory4List";
    public static final String SAVE_HELP = BASE_URL + "MotorHelp_SaveUsersDetails";
    public static final String GET_MY_ISSUE_LIST = BASE_URL + "GetissueLists";
    public static final String GET_MY_ISSUE_DETAIL = BASE_URL + "GetIssueDetails";
    public static final String CLAIM_STATUS_POLICY = BASE_URL + "UnivSompo_UserListofPolicy";
    public static final String GET_TRACKING_DETAIL1 = BASE_URL + "UnivSompo_UserClaimStatus";
    public static final String URL_REGISTER_NO_USER = BASE_URL + "UsgiUserRegistration";
    public static final String UPDATE_CUSTOMER_ID = BASE_URL + "UpdateUserClientUserId";
    public static final String BUY_POLICY_URL = BASE_URL + "GetProductManageUrl";
    public static final String BUY_VehicleManufacturer_Master = BASE_URL + "VehicleMake_Master";
    public static final String BUY_VehicleModel_Master = BASE_URL + "VehicleModel_Master";
    public static final String BUY_VehicleRtoState = BASE_URL + "VehicleRtoState";
    public static final String BUY_VehicleMasterRtoLocationZone = BASE_URL + "VehicleMasterRtoLocationZone";
    public static final String BUY_VehicleMotorQuotation = BASE_URL + "VehicleMotorQuotation";
    public static final String BUY_VehicleMotorProposal = BASE_URL + "VehicleMotorProposal";
    public static final String BUYVehicleAllCompany_Master = BASE_URL + "VehicleAllCompany_Master";
    public static final String BUYPreviousPolicyType = BASE_URL + "PreviousPolicyType";
    public static final String BUYSaveQuotationDetails = BASE_URL + "SaveQuotationDetails";
//    public static final String RENEWAL_MOTOR_URL = "http://124.124.15.42/RenewalWebAPI/api/PolicyDtls?strInputParameter=";
    public static final String RENEWAL_MOTOR_URL = "http://124.124.15.42/RenewalWebAPI/api/PolicyDtls?strInputParameter=";
    public static final String VehicleMotorBreaking = "http://124.124.15.42/BreakInInspectionUAT/Api/CreateInspection";
    public static final String VehicleMotorBreakingRefId = "http://124.124.15.42/BreakInInspectionUAT/Api/Statuscheck";
    public static final String Renewal_url = "https://www.universalsompo.com/Motor-renewal/pages/#/Home";
    public static final String Commercial_url = "https://www.universalsompo.com/MotorCommercial/";

    public static final String meta_url = "https://www.meta4u.in/";
    public static final String GET_BLOGS_VIDEOS = "http://43.242.212.119:81/AL_Mobile_App.svc/"+"GetDashboardBlogVideos";


}
